export const ROUTES = {
  dashboard: '/dashboard',
  openings: '/openings',
  openingsList: '/openings/list',
  calendar: '/calendar',
  browse: '/browse',
  browseProvider: '/browse/:providerId',
  workers: '/resources',
  appointments: '/appointments',
  appointmentDetail: '/appointments/:id',
  openingDetail: '/openings/:id',
  auth: '/auth',
  authConfirm: '/auth/confirm',
  settings: '/settings',
  profile: '/profile',
  profileSlug: '/profile/:slug',
  reports: '/reports',
  notifications: '/notifications',
  terms: '/terms',
  privacy: '/privacy',
  refund: '/refund',
  help: '/help',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
